"use strict";

const assert = require("node:assert/strict");
const { HarborModel, neutralInput } = require("../js/model.js");
const Engine = require("../js/engine.js");
const { verifyTiming } = require("../js/verification.js");
const result = verifyTiming();
assert.equal(result.passed, true);
assert.equal(result.results.length, 5);
console.log(JSON.stringify(result, null, 2));
const model = new HarborModel();
for (let i = 0; i < 1200; i++) model.update(1 / 60, { ...neutralInput(), x: -1, y: -1 });
assert.ok(model.boat.x >= 72 && model.boat.y >= 444);
assert.ok(model.smoke.length <= 14);
const visualBefore = model.snapshot();
model.visual(0.4);
assert.equal(model.snapshot(), visualBefore);
const delivery = new HarborModel();
for (const cargo of delivery.cargo) {
  delivery.boat.x = cargo.x; delivery.boat.y = cargo.y;
  delivery.interact();
  assert.equal(delivery.boat.cargo, cargo.id);
  delivery.boat.x = delivery.dock.x; delivery.boat.y = delivery.dock.y;
  delivery.boat.vx = 100; delivery.interact();
  assert.equal(delivery.boat.cargo, cargo.id);
  delivery.boat.vx = 0; delivery.interact();
  assert.equal(delivery.boat.cargo, null);
}
assert.equal(delivery.status, "won");
assert.equal(delivery.delivered, 3);
const terminal = delivery.snapshot();
delivery.update(1 / 60, { ...neutralInput(), x: 1 });
assert.equal(delivery.snapshot(), terminal);
const timeout = new HarborModel();
for (let i = 0; i < 9000; i++) timeout.update(1 / 60);
assert.equal(timeout.status, "lost");
assert.equal(timeout.remaining, 0);
const collision = new HarborModel();
collision.boat.x = collision.buoys[0].x; collision.boat.y = collision.buoys[0].y;
collision.update(1 / 60);
assert.equal(collision.boat.health, 84);
assert.equal(collision.collisions, 1);
let ticks = 0;
const engine = new Engine(() => { ticks++; });
engine.advance(0); engine.advance(5000);
assert.equal(ticks, 120);
engine.advance(5000); engine.advance(5000);
assert.equal(ticks, 300);
engine.synchronize(100000); engine.advance(100000);
assert.equal(ticks, 300);
console.log("PASS: boundaries, bounded particles, render purity, pickup, delivery, docking speed, win, timeout, collision, catch-up, pause synchronization.");
